package gui;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.text.ParseException;
import javax.swing.table.*;

/**
 *
 * @author AhmedMahmoud
 */
public class spendingtrackers extends javax.swing.JFrame {

    Connection con;
    DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<Integer> spending_id = new ArrayList<>();

    public spendingtrackers() {
        initComponents();
        this.setResizable(false);
        Text_date.setDate(new java.util.Date());
//        Text_description.setText(".");
        Text_amount.setText("0");
        this.setLocationRelativeTo(null);
        dtm.addColumn("ID");
        dtm.addColumn("Category");
        dtm.addColumn("Date");
        dtm.addColumn("Amount");
        dtm.addColumn("Description");
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/company", "root", "root");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error Connectoin");
        }
        fillComboBox();
        fillTable();
    }

    private void fillComboBox() {
        try {
            category_Combobox.removeAllItems();
            PreparedStatement st = this.con.prepareStatement("select category from category_info");
            ResultSet rs = st.executeQuery();
            while (rs.next()) {

                category_Combobox.addItem(rs.getString(1));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error In Combo Box");
        }
    }

    private void fillTable() {
        dtm.setRowCount(0);
        try {
            PreparedStatement st = con.prepareStatement("select spending_Id, category, spending_date, amount, description from spending");
            ResultSet rs = st.executeQuery();
            double total = 0;
            while (rs.next()) {
                double t = rs.getDouble(4);
                total += t;
                spending_id.add(rs.getInt(1));
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String date = dateFormat.format(rs.getDate(3));
                dtm.addRow(new Object[]{rs.getInt(1), rs.getString(2), date, rs.getDouble(4), rs.getString(5)});
            }

            Total_amount.setText(total + "");
            Table.setModel(dtm);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error In Fill Table");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Text_amount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        category_Combobox = new javax.swing.JComboBox<>();
        Add_new_category_btn = new javax.swing.JButton();
        Add_btn = new javax.swing.JButton();
        Text_date = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        Text_description = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Remove_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Total_amount = new javax.swing.JLabel();
        Update_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        View_spending = new javax.swing.JMenuItem();
        View_category = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        About_Project = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("spending trackers");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Expense");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Amount:");

        Text_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_amountActionPerformed(evt);
            }
        });
        Text_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_amountKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category:");

        category_Combobox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                category_ComboboxMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                category_ComboboxMouseMoved(evt);
            }
        });
        category_Combobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                category_ComboboxMouseClicked(evt);
            }
        });

        Add_new_category_btn.setText("Add New Catgory");
        Add_new_category_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_new_category_btnActionPerformed(evt);
            }
        });

        Add_btn.setBackground(new java.awt.Color(255, 255, 0));
        Add_btn.setText("ADD");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        Text_date.setDateFormatString("yyyy-MM-dd");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Description:");

        Text_description.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Text_date, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_description)
                        .addGap(84, 84, 84)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add_new_category_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(category_Combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(category_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 19, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Text_description, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(Add_new_category_btn))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Text_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Category", "Amount", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.getTableHeader().setReorderingAllowed(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Table Data:");

        Remove_btn.setText("Remove");
        Remove_btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Remove_btnMouseMoved(evt);
            }
        });
        Remove_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Remove_btnMouseExited(evt);
            }
        });
        Remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_btnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel6.setText("Total Amount:");

        Total_amount.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Total_amount.setText("0");
        Total_amount.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Total_amountAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Update_btn.setText("Update");
        Update_btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Update_btnMouseMoved(evt);
            }
        });
        Update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Update_btnMouseExited(evt);
            }
        });
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        jMenu3.setText("Actions");

        View_spending.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        View_spending.setText("View all Spending");
        View_spending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_spendingActionPerformed(evt);
            }
        });
        jMenu3.add(View_spending);

        View_category.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        View_category.setText("Add/View Category");
        View_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_categoryActionPerformed(evt);
            }
        });
        jMenu3.add(View_category);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Exit.setText("Exist App");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu3.add(Exit);
        jMenu3.add(jSeparator1);

        jMenu1.setText("more");

        About_Project.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        About_Project.setText("About App");
        About_Project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_ProjectActionPerformed(evt);
            }
        });
        jMenu1.add(About_Project);

        jMenu3.add(jMenu1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Remove_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Remove_btn)
                    .addComponent(Update_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        // TODO add your handling code here:

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(Text_date.getDate());

        double amount = Double.parseDouble(Text_amount.getText());

        String category = category_Combobox.getSelectedItem().toString();
        String descriptonin = Text_description.getText();

        if (amount != 0 && !category.isEmpty() && !Text_description.getText().isEmpty()) {
            try {
//                dtm.setRowCount(0);
                PreparedStatement st = con.prepareStatement("insert into spending (category, spending_date, amount, description) values(?, ?, ?, ?) ");
                st.setString(1, category);
                st.setString(2, date);
                st.setDouble(3, amount);
                st.setString(4, descriptonin);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Added Successfully");
                fillTable();
                {
                    Text_date.setDate(null);
                    Text_amount.setText("");
                    category_Combobox.setSelectedIndex(0);
                    Text_description.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error In Add");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Missed Data");
        }
    }//GEN-LAST:event_Add_btnActionPerformed

    private void Add_new_category_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_new_category_btnActionPerformed
        // TODO add your handling code here:
        new category().setVisible(true);
    }//GEN-LAST:event_Add_new_category_btnActionPerformed

    private void Remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_btnActionPerformed
        // TODO add your handling code here:
        if (Table.getSelectedRow() != -1) {
            int id = (int) Table.getValueAt(Table.getSelectedRow(), 0);

            try {
                PreparedStatement st = con.prepareStatement("delete from spending where spending_Id = ?");
                st.setInt(1, id);
                System.out.println("Removed Id->" + id);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Removed Successfully");
                System.out.println("Removed Row Index-> " + Table.getSelectedRow());
                fillTable();
                Text_date.setDate(null);
                Text_amount.setText("");
                category_Combobox.setSelectedIndex(0);
                Text_description.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error in Remove");
            }
        } else if (Table.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Empty Table");
        } else {
            JOptionPane.showMessageDialog(null, "Select Row!");
        }
    }//GEN-LAST:event_Remove_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed

        if (Table.getSelectedRow() != -1) {
            String category = category_Combobox.getSelectedItem().toString();
            Double amount = Double.parseDouble(Text_amount.getText());
            String description = Text_description.getText();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(Text_date.getDate());
            int id = (int) Table.getValueAt(Table.getSelectedRow(), 0);
            try {
                // TODO add your handling code here:
                PreparedStatement st = con.prepareStatement("update spending set category = ?, spending_date = ?, amount = ?, description = ? where spending_id = ?");
                
                st.setString(1, category);
                st.setString(2, date);
                st.setDouble(3, amount);
                st.setString(4, description);
                st.setInt(5, id);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Updated Successfully");
                fillTable();

                {
                    Text_date.setDate(null);
                    Text_amount.setText("");
                    category_Combobox.setSelectedIndex(0);
                    Text_description.setText("");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error Update");
            }
        } else if(Table.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Empty Table");
        } else {
            JOptionPane.showMessageDialog(null, "Select Row!");
        }
    }//GEN-LAST:event_Update_btnActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        String dateString = Table.getValueAt(Table.getSelectedRow(), 1).toString();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date date = dateFormat.parse(dateString);
            Text_date.setDate(date);
        } catch (ParseException e) {

        }
        category_Combobox.setSelectedItem(Table.getValueAt(Table.getSelectedRow(), 2));
        Text_amount.setText(Table.getValueAt(Table.getSelectedRow(), 3).toString());
        Text_description.setText(Table.getValueAt(Table.getSelectedRow(), 4).toString());


    }//GEN-LAST:event_TableMouseClicked

    private void Text_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_amountKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_Text_amountKeyTyped

    private void Text_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_amountActionPerformed

    private void View_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_categoryActionPerformed
        // TODO add your handling code here:
        new category().setVisible(true);
    }//GEN-LAST:event_View_categoryActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void View_spendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_spendingActionPerformed
        // TODO add your handling code here:
        new Viewspending().setVisible(true);
    }//GEN-LAST:event_View_spendingActionPerformed

    private void About_ProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_ProjectActionPerformed
        // TODO add your handling code here
        new AboutProject().setVisible(true);
        
    }//GEN-LAST:event_About_ProjectActionPerformed

    private void Total_amountAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Total_amountAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_amountAncestorAdded

    private void category_ComboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_category_ComboboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_category_ComboboxMouseClicked

    private void category_ComboboxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_category_ComboboxMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_category_ComboboxMouseDragged

    private void category_ComboboxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_category_ComboboxMouseMoved
        // TODO add your handling code here:
        fillComboBox();
    }//GEN-LAST:event_category_ComboboxMouseMoved

    private void Remove_btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Remove_btnMouseMoved
        // TODO add your handling code here:
        Remove_btn.setBackground(Color.red);
    }//GEN-LAST:event_Remove_btnMouseMoved

    private void Remove_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Remove_btnMouseExited
        // TODO add your handling code here:
        Remove_btn.setBackground(Color.white);
    }//GEN-LAST:event_Remove_btnMouseExited

    private void Update_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_btnMouseExited
        // TODO add your handling code here:
        Update_btn.setBackground(Color.white);
    }//GEN-LAST:event_Update_btnMouseExited

    private void Update_btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_btnMouseMoved
        // TODO add your handling code here:
        Update_btn.setBackground(Color.green);
    }//GEN-LAST:event_Update_btnMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spendingtrackers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spendingtrackers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spendingtrackers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spendingtrackers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spendingtrackers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About_Project;
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton Add_new_category_btn;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton Remove_btn;
    private javax.swing.JTable Table;
    private javax.swing.JTextField Text_amount;
    private com.toedter.calendar.JDateChooser Text_date;
    private javax.swing.JTextField Text_description;
    private javax.swing.JLabel Total_amount;
    private javax.swing.JButton Update_btn;
    private javax.swing.JMenuItem View_category;
    private javax.swing.JMenuItem View_spending;
    private javax.swing.JComboBox<String> category_Combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
